### ISSUE TITLE
Board name with forward slashes

### ISSUE THREAD

**Issue by ArloL** [GSGBen/t2md#2]
Cool tool :)

I experimented with it and came across a small issue.

I have a board called `I would like to do consistently/routinely/regularly` and the name is not being sanitized:

```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/aokeeffe/Downloads/t2md-macos-x64/listento/t2md/I would like to do consistently/routinely/regularly.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at GoldenSyrupGames.T2MD.Cli.ProcessTrelloBoardAsync(TrelloApiBoardModel trelloApiBoard, CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.RunAsync(CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.Main(String[] args)
   at GoldenSyrupGames.T2MD.Cli.<Main>(String[] args)
zsh: abort      ./t2md --output-folder=listento
```

**Comment by GSGBen** [comment]
Thanks, this one I can test easily. I'll get a fix in soon.

**Comment by GSGBen** [comment]
@ArloL can you please try again with https://github.com/GSGBen/t2md/releases/tag/v1.0.1 and let me know if it's fixed.

**Comment by ArloL** [comment]
It works :) Thanks!
