### ISSUE TITLE
System.Net.Http.HttpRequestException 416 (Range Not Satisfiable)

### ISSUE THREAD

**Issue by ArloL** [GSGBen/t2md#4]
Using 1.0.2 I get this exception:

```
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 416 (Range Not Satisfiable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at GoldenSyrupGames.T2MD.Cli.DownloadTrelloCardAttachmentAsync(TrelloAttachmentModel attachment, String attachmentFolderPath, String cardFolderPath)
   at GoldenSyrupGames.T2MD.Cli.DownloadTrelloCardAttachmentsAsync(IEnumerable`1 uploadedAttachments, TrelloCardModel trelloCard, Int32 cardIndex, String usableCardName, String cardFolderPath)
   at GoldenSyrupGames.T2MD.Cli.ProcessTrelloCardAsync(TrelloCardModel trelloCard, Int32 cardIndex, String cardFolderPath, TrelloBoardModel trelloBoard, CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.ProcessTrelloBoardAsync(TrelloApiBoardModel trelloApiBoard, CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.RunAsync(CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.Main(String[] args)
   at GoldenSyrupGames.T2MD.Cli.<Main>(String[] args)
```

Any more data that I can provide?

**Comment by GSGBen** [comment]
Can you please run it again and let me know if it fails in the same way? I should probably add in `Polly` for retries either way.

**Comment by ArloL** [comment]
Yes, it is reproducible.

I found the json to be responsible:

```
{
    "id": "5b67f42db6f4b32ee11a2a9c",
    …
    "actions": [
        {
            …
            "data": {
                "attachment": {
                    "url": "https://trello.com/1/cards/5b67f4857460e6051d70aa7d/attachments/5b67f542be8c3a33b0301eb9/download/b%C3%B6a.txt",
                    "name": "böa.txt",
                    "id": "5b67f542be8c3a33b0301eb9"
                },
```

The URL gives me this response

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRange</Code><Message>The requested range is not satisfiable</Message><RangeRequested>bytes=0-10485759</RangeRequested><ActualObjectSize>0</ActualObjectSize><RequestId>1HT0YAY7MQJFTC52</RequestId><HostId>mwbtTlUrZMqHjTDciYSBCe3yqVWqLXAcY+IAIQyUYYn9HXrs6390fmiVF3mDeswPXqPj+JnckHs=</HostId></Error>
```

**Comment by GSGBen** [comment]
Interesting.

* Are you accessing that URL from a browser with a logged in Trello session?
* If you replace `b%C3%B6a.txt` in the URL with `böa.txt` do you get the same result?
* Can you find the attachment on the card on trello.com?
  * Can you open it from there?
  * Is the URL that opens different?

**Comment by ArloL** [comment]
- Yes
- Yes
- Yes
  - No
  - No

**Comment by GSGBen** [comment]
Sweet, so it's a Trello-side issue. Can you please try with [v1.1.0](https://github.com/GSGBen/t2md/releases/tag/v1.1.0) and the argument `--ignore-failed-attachment-downloads` and let me know if the whole process completes without an exception this time (just warnings).

**Comment by ArloL** [comment]
Works :) Thanks!
