### ISSUE TITLE
Unhandled exception: The given key 'xxx' was not present in the dictionary

### ISSUE THREAD

**Issue by alranel** [GSGBen/t2md#42]
While retrying the same import as my other report #39 I'm now getting a different error:

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'https://trello.com/c/xxx' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GoldenSyrupGames.T2MD.Cli.ReplaceLinksFileAsync(String path, CliOptions options, Dictionary`2 urlCardMap, String thisCardShortUrl)
   at GoldenSyrupGames.T2MD.Cli.ReplaceLinksCardAsync(TrelloCardModel trelloCard, CliOptions options, Dictionary`2 urlCardMap)
   at GoldenSyrupGames.T2MD.Cli.ReplaceLinksBoardAsync(TrelloBoardModel trelloBoard, CliOptions options, Dictionary`2 urlCardMap)
   at GoldenSyrupGames.T2MD.Cli.RunAsync(CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.Main(String[] args)
   at GoldenSyrupGames.T2MD.Cli.<Main>(String[] args)
```

The referenced URL brings me to a specific card of a board that I can visualize but I'm not a member of (it belongs to a workspace I'm member of), and infact is not being downloaded by t2md. Maybe another board of mine references this card?

Maybe the solution could be to catch this exception and handle it gracefully by writing a warning on the console without stopping the process.

**Comment by GSGBen** [comment]
Thanks for the details, this one makes sense.
