### ISSUE TITLE
Response status code does not indicate success: 429 (Too Many Requests)

### ISSUE THREAD

**Issue by mcaple** [GSGBen/t2md#45]
Excellent utility but when I ran this for the first time today I received

Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoldenSyrupGames.T2MD.Cli.GetBoardCommentsAsync(String boardID)
   at GoldenSyrupGames.T2MD.Cli.ProcessTrelloBoardAsync(TrelloApiBoardModel trelloApiBoard, CliOptions options, Dictionary`2 duplicateBoardSuffixes)
   at GoldenSyrupGames.T2MD.Cli.RunAsync(CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.Main(String[] args)
   at GoldenSyrupGames.T2MD.Cli.<Main>(String[] args)

**Comment by GSGBen** [comment]
Thanks for the report!

Yep, this and 503 errors happen intermittently. I'll definitely need to add
a retry handler.

For now you might or might not be able to get past it by running again a
few times.

**Comment by makebreaker** [comment]
I'm having the same issue, it appears to be an issue with trello's API rate limiting, not sure if it's because I'm a free trello user or not. 

From the trello API docs ". There is a limit of 300 requests per 10 seconds for each API key and 100 requests per 10 second interval for each token."; [the relevant trello doc]( https://developer.atlassian.com/cloud/trello/guides/rest-api/rate-limits/)

Would it be possible to add a rate limit flag? I'm fine if it's slow, I just want to export all my data off trello finally :)

**Comment by combs** [comment]
note to anyone else trying the "export in chunks" approach--t2md clears the folder at the beginning of each run... so don't try to use the same output folder for each chunk!

**Comment by jwarlander** [comment]
I've implemented a patch that wraps HttpClient and does rate limiting. It seems to have worked fine with my 116 boards, as far as avoiding 429 errors at least 😅 Would it be of interest as a PR, @GSGBen?

**Comment by GSGBen** [comment]
Ooh nice, yes please!
