### ISSUE TITLE
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by zenminimalist** [GSGBen/t2md#52]
I'm getting the following error after the following command:

`Test@MacBook-Air-M1 t2md % t2md --output-folder /Users/Test/Downloads/export /Users/Test/Downloads/t2md`

I put the MacOS binary in my User/bin folder. Not sure what is going on here. Or am I missing something?

```
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GoldenSyrupGames.T2MD.Cli.RunAsync(CliOptions options)
   at GoldenSyrupGames.T2MD.Cli.Main(String[] args)
   at GoldenSyrupGames.T2MD.Cli.<Main>(String[] args)
zsh: abort      t2md --output-folder /Users/Test/Downloads/export /Users/Test/Downloads/t2m`

**Comment by zenminimalist** [comment]
Just to add. 
As it's **not** working for me, is there a way I can use my exported trello.json (which I exported manually) and have the app convert it for me locally?

**Comment by GSGBen** [comment]
Hey @zenminimalist, this seems like something between the app and Trello causing the issue.

- do you have any deep SSL/TLS inspection running? E.g. do you have a firewall with web filtering, or are you at work where your network team might be running it?
- Can you browse to https://trello.com from the device you're running this on, check the certificate chain (usually under the lock icon in the address bar) and share a screenshot here?

For your second question: unfortunately no, it doesn't support just reading from the json file. This is because the json file isn't a full export - it only contains the last 1000 actions, and comments are actions, so using that method can miss some data.

**Comment by zenminimalist** [comment]
@GSGBen Thanks for the reply. 

I managed to get it working unconsciously, by restarting the Mac. That fixed it. No idea what the problem was related to.
